### ISSUE TITLE
Up-to-date documentation

### ISSUE THREAD

**Issue by jliuhtonen** [poetix/protonpack#11]
The javadoc in StreamUtils is pretty good, but the README's documentation is outdated. There should be a way to keep the docs automatically up to date. 

Perhaps the outdated documentation could be removed and a link provided to the javadocs or maybe there is a way to generate README from the javadocs.

**Comment by alexcrt** [comment]
We could also create a branch gh-pages where we put the javadoc online; so people can browse it.

**Comment by jliuhtonen** [comment]
That would be one way to accomplish this, yes.

**Comment by poetix** [comment]
I would like to encourage anyone who has submitted or is thinking of submitting a pull request to include a suitable update to the README, which should present a concise summary of what's included, separate from the javadocs.

+1 to the online javadoc suggestion. I'll look into this when I get a moment.

**Comment by poetix** [comment]
Docs now at http://poetix.github.io/protonpack
