### ISSUE TITLE
Re-organization of the classes

### ISSUE THREAD

**Issue by alexcrt** [poetix/protonpack#14]
As the library is growing, maybe we could create some packages to have a cleaner structure. I was thinking of something like this:

![capture d ecran 2015-03-12 a 17 18 33](https://cloud.githubusercontent.com/assets/8796889/6622250/d7ee345c-c8db-11e4-8c90-c68bc25d66e3.png)

Any thoughts?

**Comment by poetix** [comment]
I think the Spliterators should remain package-private, as there's no reason to expose them directly. Therefore they would have to be in the same package as StreamUtils. No objection to pulling out selector and function.

**Comment by alexcrt** [comment]
This is indeed a good point. I think there's no rush at the moment, but I guess it's good in the future to think about some structure and to avoid the all-in-one package.

**Comment by poetix** [comment]
I've pulled out selectors, functions and maps.
