### ISSUE TITLE
interleaveMerge Stream

### ISSUE THREAD

**Issue by fbastian** [poetix/protonpack#20]
I would like to use an interleave `Stream`, for an arbitrary number of source `Stream`s, based on `Selectors.takeMin(Comparator)`, but when the `Comparator` returns 0, I would like the equal `Stream` elements to be merged based on a merge function provided. And the elements to be progressively merged as long as the source `Stream`s returned equal elements. 

Is is something doable with the current implementation? If not, is it something you might consider implementing?

Thanks.

**Comment by poetix** [comment]
I would suggest writing a custom Spliterator based on those included in protonpack. I'm not sure that this use case is general enough to merit inclusion, although if you can describe a common scenario where it might be wanted I'll reconsider. Or you could raise a PR with your implementation...
