### ISSUE TITLE
MapStream method to reduce (key,value) pairs to a regular Stream

### ISSUE THREAD

**Issue by michaelbannister** [poetix/protonpack#27]
Would you consider a method on MapStream<K,V> which takes a BiFunction<K,V,R> to convert an entry to an object of type R?

This is a common requirement in my application. I'd be happy to try my hand at creating this and submitting a pull request if you think it would be a good candidate for inclusion.

**Comment by poetix** [comment]
Sounds like a good idea. Send me a PR!

**Comment by poetix** [comment]
Changes included in new release 1.9, now in Maven Central.
