### ISSUE TITLE
Missing `takeWhileInclusive`, `takeUntilInclusive`, etc

### ISSUE THREAD

**Issue by maria-camenzuli** [poetix/protonpack#33]
I just came across a situation where I needed an inclusive version of `takeWhile`. This operator would take elements from a stream until but including the first element that does not match the given predicate.

It would be great if we could add `takeWhileInclusive` to the protonpack, along with inclusive versions of other operators like `takeUntil`, `skipWhile`, etc.

**Comment by poetix** [comment]
That makes sense. It might be a while before I have time to do it myself - would you like to raise a pull request?

**Comment by maria-camenzuli** [comment]
Yes I can.

**Comment by poetix** [comment]
I've merged your changes and released a new 1.13 version, which should be available in Maven Central within the next 24 hours. Thanks for your contribution!
