### ISSUE TITLE
Additions to MapStream

### ISSUE THREAD

**Issue by tomwhoiscontrary** [poetix/protonpack#35]
Things i've run into which i need:

* mapEntryToLong, eg with `(k, v) -> ((long) k.hashCode()) << 32 + v.hashCode()`, and potentially the int and double versions, for parity with Stream

* mappingEntriesToValues, eg with `(t, e) -> e + " happened at " + t`

Do those make sense? I will try for a PR if so.

**Comment by alexcrt** [comment]
Isn't the `mappingEntriesToValues` the same as using the `mapEntries` method which takes a bi-function (K, V) -> R as parameter and returns a stream of type R ?

Similarly, `mapEntryToLong` can be currently seen as a `mapEntries(BiFunction<K,V,Long>).mapToLong(identity())` (which could be your current workaround). But if you want a method that turns a `MapStream<K,V>` into a `LongStream`, we'd effectively need to implement a `mapEntries(ToLongBiFunction<K, V>`) in the API.

**Comment by tomwhoiscontrary** [comment]
mappingEntriesToValues should produce a MapStream. Sorry, my examples are terrible. I have a Map<String, Integer> and a BiFunction<String, Integer, Double>, and i want to produce a Map<String, Double> where the the keys are the same as in the original map, and the values are the result of evaluating the function on the key and value of an entry. The existing mapEntries takes me into the realm of ordinary Stream, and getting back to a Map from there is a bit of a pain.

You're right that i can still get to a LongStream from a MapStream as you describe, but it's enough extra code that i've stuck with a Stream<Map.Entry>.

**Comment by alexcrt** [comment]
Oh I see. Well yes we should add a method that take a `BiFunction` as parameter to map the values, it should look to something like this:

```default <V1> MapStream<K, V1> mapValues(BiFunction<? super K, ? super V, ? extends V1> mapper) {
    return new DefaultMapStream<>(map(e -> new SimpleImmutableEntry<>(e.getKey(), mapper.apply(e.getKey(), e.getValue()))));
    }
```
As a current workaround, I guess you could use `.mapEntries((k, v) -> MapStream.of(k, k + v)).flatMap(m -> m)`

**Comment by poetix** [comment]
Applied in 1.14 release.
