### ISSUE TITLE
Indexed<T> should provide a toString() implementation.

### ISSUE THREAD

**Issue by Aklakan** [poetix/protonpack#37]
```java
Indexed<String> foo = Indexed.index(0l, "foo");
System.out.println(foo);
```
yields: `com.codepoetics.protonpack.Indexed@6239600c` but would be more human friendly if it returned the content, such as `0: foo`, `0 -> foo`, or `(0, foo)`.

**Comment by poetix** [comment]
Applied in 1.14 release
