### ISSUE TITLE
A collector which forces eager evaluation of a stream

### ISSUE THREAD

**Issue by tomwhoiscontrary** [poetix/protonpack#39]
I end up needing this quite often when dealing with async stuff. Here's mine:

    private static <T> Collector<T, ?, Stream<T>> force() {
        return Collectors.collectingAndThen(Collectors.toList(), List::stream);
    }

So you can say something like:

    Set<String> rappers = loadRappers();
    Set<String> causesOfDeath = rappers.stream()
        .map(causeOfDeathService::findCauseOfDeathAsync)
        .collect(force())
        .flatMap(swallowingExceptions(Future::get))
        .collect(Collectors.toSet());

The point being that without the force, this pipeline will send one request, then wait for it to come back, then send another, etc, whereas with the force, the portion of the pipeline above the force will run for everything before the portion after.

**Comment by poetix** [comment]
Not what you're asking for, but relatedly: has https://github.com/poetix/protonpack/blob/master/src/main/java/com/codepoetics/protonpack/collectors/CompletableFutures.java been drawn to your attention?

**Comment by tomwhoiscontrary** [comment]
I have indeed seen that. As it happens, it's not what i need for two reasons.

One, if i've understood it correctly, it complects the forcing of the future-spawning operation with the act of waiting for it; that is what you want to do in many situations, and in my motivating example, but sadly not in my actual situation. As each future completes, i want to kick off another request based on the result. This is because i'm using an API designed by sadists.

Two, the client library i'm using doesn't actually deal in Futures, but in a home-grown alternative with slightly different and more akward semantics. This is because the client library was designed by the same sadists.

**Comment by tomwhoiscontrary** [comment]
I just thought of another thing that's even more tangential. I want something like this all over:

    public static <T, E extends Throwable> T raise(E e) throws E {
      throw e;
    }

I'm not mad, you know. I want this for when i need to throw an exception from expression position. T doesn't really mean T, here, it means ⊥. The famous throwingMerger() is a special case of this. I also find myself writing:

    Widget reformGrommet(Grommet grommet) {
        if (grommet.getWeight() > 7) return Widget.of(grommet.reform());
        else throw new ImpossibleManufactureException();
    }

And i would like to write:

    Widget reformGrommet(Grommet grommet) {
        return (grommet.getWeight() > 7) ? Widget.of(grommet.reform()) : raise(new ImpossibleManufactureException());
    }

Okay that's an awful example

I wonder if this is because i've got used to using Result and ? for error handling in Rust.

**Comment by poetix** [comment]
Would be tempted to use an [Either](https://github.com/poetix/ambivalence) type for the latter cases. Plays nicer with lambdas generally, which don't work well with checked exceptions.

**Comment by tomwhoiscontrary** [comment]
The ergonomics of Eithers in Java are so horrible that, IMHO, they're not worth using, despite their many advantages in principle. They also don't address some of my specific uses for this abomination.

However, i recognise that it is not at all in the theme or spirit of protonpack, so please ignore it.
