### ISSUE TITLE
zip3

### ISSUE THREAD

**Issue by leventov** [poetix/protonpack#4]
Zip3 would be useful.
New interface is also required for that:
```
@FunctionalInterface
interface TriFunction<A,B,C,R> {

    R apply(A a, B b, C c);

    default <V> TriFunction<A, B, C, V> andThen(
                                Function<? super R, ? extends V> after) {
        Objects.requireNonNull(after);
        return (A a, B b, C c) -> after.apply(apply(a, b, c));
    }
}
```

(This is not theoretical "good thing to have", I actually just needed zip3, workarounded by 2 nested `zip` calls fo far.)

**Comment by poetix** [comment]
In protonpack 1.2, just released, should be in Maven Central soon.
