### ISSUE TITLE
Equivalent of partition in Clojure

### ISSUE THREAD

**Issue by alexcrt** [poetix/protonpack#9]
I think it would be useful to obtain a partitionned `Stream<List<T>>` from a `Stream<T>` like the [partition](https://clojuredocs.org/clojure.core/partition) function in Clojure. 

For example:

`partitionned(Stream.of(1, 2, 3, 4, 5), 3, 1)` would result in a `Stream([1, 2, 3], [2, 3, 4], [3, 4, 5])`.

The aggregate spliterator have a similar behavior if the step is equals to the size of list we want, but maybe we could improve it?

What do you think?

**Comment by poetix** [comment]
Presumably some kind of buffer-release mechanism would be involved. Doesn't seem like it would be _too_ difficult to implement.

As a matter of interest, what's the (or what's _a_) use case?

**Comment by alexcrt** [comment]
Inspired by this StackOverflow thread:

http://stackoverflow.com/questions/20470010/java-8-collect-successive-pairs-from-a-stream/28858672

Although there might be real-word use cases, but I didn't think of them atm.

**Comment by alexcrt** [comment]
See PR #10
